G: 1 / (x -a); // x ではなく s にするとsubst が失敗する
PID: Kp + Ki/x + Kd*x;
T1: rat(G*PID / (1 - G*PID));
T2: expand(Y * denom(T1) + num(T1) * X);
T3: ratsubst(z, x^2 * Y, T2);
T4: rhs(solve(T3, z)[1]);
rat(subst(s,x,T4));

//                                                    2
//    Ki X - Ki Y + (((- a) - Kp) Y + Kp X) s + Kd X s
//    -------------------------------------------------
//                         Kd - 1
//
